### PR TITLE
Updating to Spin SDK 3.0.1

### PR DESCRIPTION
**Pull request by mikkelhegn**

### CODE REVIEW

**Comment by karthik2804** [comment]
#16 seems to do the same.

**Review by vdice — APPROVED** [review]

**Comment by mikkelhegn** [comment]
> #16 seems to do the same.

Ahh - sorry @vdice didn't catch that one...

**Comment by mikkelhegn** [comment]
@vdice - Like this?

**Comment by vdice** [comment]
@mikkelhegn Yes!

**Pull request merged**
